-- Supabase bootstrap for the public family-home template.
-- Run this in a NEW Supabase project owned by the deployer.
-- Do not run it against someone else's production project.

create extension if not exists pgcrypto;

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  category text not null default 'general',
  duedate date,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  expiry_date date,
  details jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'done')),
  attachment_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tasks_owner_duedate_idx on public.tasks (owner_id, duedate);

alter table public.tasks enable row level security;

drop policy if exists "users read own tasks" on public.tasks;
drop policy if exists "users insert own tasks" on public.tasks;
drop policy if exists "users update own tasks" on public.tasks;
drop policy if exists "users delete own tasks" on public.tasks;

create policy "users read own tasks"
on public.tasks for select
to authenticated
using (owner_id = auth.uid());

create policy "users insert own tasks"
on public.tasks for insert
to authenticated
with check (owner_id = auth.uid());

create policy "users update own tasks"
on public.tasks for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

create policy "users delete own tasks"
on public.tasks for delete
to authenticated
using (owner_id = auth.uid());

revoke all on public.tasks from anon;
grant select, insert, update, delete on public.tasks to authenticated;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  unique (owner_id, endpoint)
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;

create policy "users manage own push subscriptions"
on public.push_subscriptions
for all
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

revoke all on public.push_subscriptions from anon;
grant select, insert, update, delete on public.push_subscriptions to authenticated;

insert into storage.buckets (id, name, public)
values ('attachments', 'attachments', false)
on conflict (id) do update set public = false;

drop policy if exists "users read own attachments" on storage.objects;
drop policy if exists "users upload own attachments" on storage.objects;
drop policy if exists "users update own attachments" on storage.objects;
drop policy if exists "users delete own attachments" on storage.objects;

create policy "users read own attachments"
on storage.objects for select
to authenticated
using (
  bucket_id = 'attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "users upload own attachments"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "users update own attachments"
on storage.objects for update
to authenticated
using (
  bucket_id = 'attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "users delete own attachments"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);
